# The labels in this file are automatically synced with the repository
# using the micnncim/action-label-syncer action.
---
- name: dependencies
  color: 0366d6
  description: "Pull requests that update a dependency file"
- name: documentation
  color: 0075ca
  description: "Improvements or additions to documentation"
- name: PR-block
  color: 3498db
  description: "Pull Request: Do not merge"
- name: PR-merge
  color: 3498db
  description: "Pull Request: Merge when ready"
- name: bug
  color: ee0701
  description: "Bug Report"
- name: triage
  color: 0c9cf2
  description: "Needs Triaging"
- name: feature
  color: dc8b10
  description: "New feature or request"
- name: invalid
  color: e4e669
  description: "This doesn't seem right"
- name: duplicate
  color: 000000
  description: "This issue or pull request already exists"
- name: patch
  color: 834dd1
  description: "Change leading to a patch level version bump"
- name: minor
  color: 764ab5
  description: "Change leading to a minor level version bump"
- name: major
  color: 6b3bad
  description: "A (breaking) change leading to a major version bump"
- name: wontfix
  color: ffffff
  description: "This will not be worked on"
- name: question
  color: d876e3
  description: "Further information is requested"
